openapi: 3.0.0
x-stoplight:
  id: tsnuvw4jm6mj0
info:
  title: ChuckNorris
  version: '1.0'
servers:
  - url: 'https://api.chucknorris.io/jokes'
paths:
  /random:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Joke'
      operationId: get-jokes
      description: Returns a random joke.
    parameters: []
  /categories:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-jokes-categories
      description: Returns all the categories
    parameters: []
components:
  schemas:
    Joke:
      type: object
      properties:
        categories:
          type: array
          items:
            type: object
            properties: {}
        created_at:
          type: string
        icon_url:
          type: string
        id:
          type: string
        updated_at:
          type: string
        url:
          type: string
        value:
          type: string
      x-examples:
        Example 1:
          categories: []
          created_at: '2020-01-05 13:42:26.447675'
          icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png'
          id: RtqvU-4UR12whu1GrNVEWg
          updated_at: '2020-01-05 13:42:26.447675'
          url: 'https://api.chucknorris.io/jokes/RtqvU-4UR12whu1GrNVEWg'
          value: Chuck Norris house trained his dog by 1 roundhouse kick to the face.
